### PR TITLE
salt bug workaround

### PR DESCRIPTION
**Pull request by lsh-0**
this may fix https://github.com/saltstack/salt/issues/42550

from what I read the fix was only applied to 2016.11 +

### CODE REVIEW

**Comment by lsh-0** [comment]
@giorgiosironi , I think this is failing because the bug is present in the `master` branch and the PR that merged that change in was pre-formula CI.

In this state, this PR and all subsequent PRs will never pass because a machine can't be brought up cleanly. This change works in Vagrant so I'm going to merge it in and test it on the `continuumtest` instance that has the same problem.

**Comment by lsh-0** [comment]
`continuumtest` updates fine.

**Comment by giorgiosironi** [comment]
On the Salt change, I think this is the right fix as we do this in other projecs. To be able to see the injected `identity` you need to be root as the Salt bug describes.

On the build change, our pattern is to always build the `master` of the formula first, and then apply the change. I don't know if there is a way yet to tell a masterless instance to use a branch of a formula for their first Salt highstate. At that point we could build both "starting from the master and switching" and "starting from this branch" to compare.

**Comment by lsh-0** [comment]
> I don't know if there is a way yet to tell a masterless instance to use a branch of a formula for their first Salt highstate.

I could probably come up with something, but I think what we have now works well. I'd need a more compelling case than this to go ahead and implement that.

> At that point we could build both "starting from the master and switching" and "starting from this branch" to compare.

hopefully it's just a short transitional state while formulas get migrated into CI

**Comment by giorgiosironi** [comment]
True that it is transitional, but there are still distinct use cases:

1. applying the formula to an existing stack/server
2. creating a new stack/server

We test 1, but not 2 (only creating 2 with the `master` version instead)

**Comment by lsh-0** [comment]
I'm still overjoyed we have masterless instances and formulas going through CI to be honest.

Testing the creation of new instances definitely should be done. I don't think any minor thing like this will justify it but bringing up a new instance and seeing it go through 100+ states successfully is a grand feeling. I'll open a ticket to add support to builder

**Pull request merged**
